### ISSUE TITLE
Feature request: Get status of Window/Door Contacts

### ISSUE THREAD

**Issue by Andirs55** [mortommy/mycroft-skill-openhab#11]
Hey it would be cool if one could ask Mycroft if a certain window or door is opened or closed.

E.g.:

"Hey Mycroft, is the Bedroom window open?"
"Hey Mycroft, is the Bedroom window opened?"
"Hey Mycroft, is the Bedroom window closed?"

Thanks :)

**Comment by mortommy** [comment]
This issue was moved to openhab/openhab-mycroft#2
