### ISSUE TITLE
Move skill to openHAB Github

### ISSUE THREAD

**Issue by kaikreuzer** [mortommy/mycroft-skill-openhab#12]
As discussed in https://github.com/openhab/openhab-docs/issues/495#issuecomment-327770946, we should make this an official integration and thus move the skill to the openHAB github organisation.

Looking at the existing [commit history](https://github.com/mortommy/mycroft-skill-openhab/commits/master) I would think that it is best to start a new repo with a single initial commit, since the current commits hardly have any commit messages and aren't signed-off.

@mortommy If this is ok with you, please push the current code as an initial commit to https://github.com/openhab/openhab-mycroft (on which you are admin).
It would be nice if you could include a CONTRIBUTING.md file (similar to the one in the [alexa skill](https://github.com/openhab/openhab-alexa/blob/master/CONTRIBUTING.md) and also make sure that you yourself (as the maintainer of the repo) follow these guidelines (which we adopt in all openHAB repos). If you have any questions, please let me know!

**Comment by mortommy** [comment]
Hi @kaikreuzer ,
thank you! I have a question, it seems I'm not admin of the new repo neither I have write permissions. Do I need to fork the project and go for a PR as usual?
Thank you.

**Comment by kaikreuzer** [comment]
It looks as if you still need to confirm the invitation:

<img width="676" alt="screen shot 2017-09-08 at 10 10 01" src="https://user-images.githubusercontent.com/3244965/30202235-f71220bc-947d-11e7-8570-b9f7833431c7.png">

You should be able to do so through this link: https://github.com/openhab/openhab-mycroft/invitations

But even as a maintainer, it is a good idea to do your own contributions from a personal fork through PRs, yes!

**Comment by mortommy** [comment]
ooops. (I didn't receive any notification )
Great! Thank you.

**Comment by mortommy** [comment]
pushed!

**Comment by mortommy** [comment]
added CONTRIBUTING.md file.
