### ISSUE TITLE
Fix occurance of OpenHab

### ISSUE THREAD

**Issue by ThomDietrich** [mortommy/mycroft-skill-openhab#7]
Hey, me once more ;)

There are a few places throughout your README and code where you are mentioning one of Openhab, OpenHab, OpenHAB or OH. It was once decided to establish "openHAB" as the only valid name.

e.g. 
https://github.com/mortommy/mycroft-skill-openhab/blob/0495b468b525924155354e25e7f28ea668b7a508/__init__.py#L36

**Comment by mortommy** [comment]
Occurance of OpenHab just fixed.
