### ISSUE TITLE
Translations and a thought on management

### ISSUE THREAD

**Issue by ThomDietrich** [mortommy/mycroft-skill-openhab#9]
Heyho!
Soon users might want to add other languages to your skill. It will be hard to keep all command options in sync between the different language files.

There are special services that help manage translations. Some of those can be integrated with GitHub. You should have a look! Just yesterday integration of a new service was announced through the GitHub blog: https://github.com/blog/2427-extend-your-workflow-with-these-new-marketplace-apps -> "Localization"

Also:
* https://github.com/marketplace/category/localization
* https://github.com/works-with/category/localization

**Comment by mortommy** [comment]
Thank you. I'll have a look.

**Comment by mortommy** [comment]
This issue was moved to openhab/openhab-mycroft#1
